Template.children.helpers({
  id: function () {
    return Template.instance().data;
  }
});

var f = function(that) {
  var vm = new Vue({
    el: '#child' + that.data,
    data: {
      'text1': 'Hello',
      'text2': 'Hello',
      'text3': 'Hello',
      'text4': 'Hello',
      'text5': 'Hello',
      'text6': 'Hello',
      'text7': 'Hello',
      'text8': 'Hello',
      'text9': 'Hello',
      'text10': 'Hello',
      'text11': 'Hello',
      'text12': 'Hello',
      'text13': 'Hello',
      'text14': 'Hello',
      'text15': 'Hello',
      'text16': 'Hello',
      'text17': 'Hello',
      'text18': 'Hello',
      'text19': 'Hello',
      'text20': 'Hello',
      'text21': 'Hello',
      'text22': 'Hello',
      'text23': 'Hello',
      'text24': 'Hello',
      'text25': 'Hello',
      'text26': 'Hello',
      'text27': 'Hello',
      'text28': 'Hello',
      'text29': 'Hello',
      'text30': 'Hello',
      'text31': 'Hello',
      'text32': 'Hello',
      'text33': 'Hello',
      'text34': 'Hello',
      'text35': 'Hello',
      'text36': 'Hello',
      'text37': 'Hello',
      'text38': 'Hello',
      'text39': 'Hello',
      'text40': 'Hello',
      'text41': 'Hello',
      'text42': 'Hello',
      'text43': 'Hello',
      'text44': 'Hello',
      'text45': 'Hello',
      'text46': 'Hello',
      'text47': 'Hello',
      'text48': 'Hello',
      'text49': 'Hello',
      'text50': 'Hello',
      'text51': 'Hello',
      'text52': 'Hello',
      'text53': 'Hello',
      'text54': 'Hello',
      'text55': 'Hello',
      'text56': 'Hello',
      'text57': 'Hello',
      'text58': 'Hello',
      'text59': 'Hello',
      'text60': 'Hello',
      'text61': 'Hello',
      'text62': 'Hello',
      'text63': 'Hello',
      'text64': 'Hello',
      'text65': 'Hello',
      'text66': 'Hello',
      'text67': 'Hello',
      'text68': 'Hello',
      'text69': 'Hello',
      'text70': 'Hello',
      'text71': 'Hello',
      'text72': 'Hello',
      'text73': 'Hello',
      'text74': 'Hello',
      'text75': 'Hello',
      'text76': 'Hello',
      'text77': 'Hello',
      'text78': 'Hello',
      'text79': 'Hello',
      'text80': 'Hello',
      'text81': 'Hello',
      'text82': 'Hello',
      'text83': 'Hello',
      'text84': 'Hello',
      'text85': 'Hello',
      'text86': 'Hello',
      'text87': 'Hello',
      'text88': 'Hello',
      'text89': 'Hello',
      'text90': 'Hello',
      'text91': 'Hello',
      'text92': 'Hello',
      'text93': 'Hello',
      'text94': 'Hello',
      'text95': 'Hello',
      'text96': 'Hello',
      'text97': 'Hello',
      'text98': 'Hello',
      'text99': 'Hello',
      'text100': 'Hello'

    },
    methods: {
      click1: function (e) { console.log('X'); },
      click2: function (e) { console.log('X'); },
      click3: function (e) { console.log('X'); },
      click4: function (e) { console.log('X'); },
      click5: function (e) { console.log('X'); },
      click6: function (e) { console.log('X'); },
      click7: function (e) { console.log('X'); },
      click8: function (e) { console.log('X'); },
      click9: function (e) { console.log('X'); },
      click10: function (e) { console.log('X'); },
      click11: function (e) { console.log('X'); },
      click12: function (e) { console.log('X'); },
      click13: function (e) { console.log('X'); },
      click14: function (e) { console.log('X'); },
      click15: function (e) { console.log('X'); },
      click16: function (e) { console.log('X'); },
      click17: function (e) { console.log('X'); },
      click18: function (e) { console.log('X'); },
      click19: function (e) { console.log('X'); },
      click20: function (e) { console.log('X'); },
      click21: function (e) { console.log('X'); },
      click22: function (e) { console.log('X'); },
      click23: function (e) { console.log('X'); },
      click24: function (e) { console.log('X'); },
      click25: function (e) { console.log('X'); },
      click26: function (e) { console.log('X'); },
      click27: function (e) { console.log('X'); },
      click28: function (e) { console.log('X'); },
      click29: function (e) { console.log('X'); },
      click30: function (e) { console.log('X'); },
      click31: function (e) { console.log('X'); },
      click32: function (e) { console.log('X'); },
      click33: function (e) { console.log('X'); },
      click34: function (e) { console.log('X'); },
      click35: function (e) { console.log('X'); },
      click36: function (e) { console.log('X'); },
      click37: function (e) { console.log('X'); },
      click38: function (e) { console.log('X'); },
      click39: function (e) { console.log('X'); },
      click40: function (e) { console.log('X'); },
      click41: function (e) { console.log('X'); },
      click42: function (e) { console.log('X'); },
      click43: function (e) { console.log('X'); },
      click44: function (e) { console.log('X'); },
      click45: function (e) { console.log('X'); },
      click46: function (e) { console.log('X'); },
      click47: function (e) { console.log('X'); },
      click48: function (e) { console.log('X'); },
      click49: function (e) { console.log('X'); },
      click50: function (e) { console.log('X'); },
      click51: function (e) { console.log('X'); },
      click52: function (e) { console.log('X'); },
      click53: function (e) { console.log('X'); },
      click54: function (e) { console.log('X'); },
      click55: function (e) { console.log('X'); },
      click56: function (e) { console.log('X'); },
      click57: function (e) { console.log('X'); },
      click58: function (e) { console.log('X'); },
      click59: function (e) { console.log('X'); },
      click60: function (e) { console.log('X'); },
      click61: function (e) { console.log('X'); },
      click62: function (e) { console.log('X'); },
      click63: function (e) { console.log('X'); },
      click64: function (e) { console.log('X'); },
      click65: function (e) { console.log('X'); },
      click66: function (e) { console.log('X'); },
      click67: function (e) { console.log('X'); },
      click68: function (e) { console.log('X'); },
      click69: function (e) { console.log('X'); },
      click70: function (e) { console.log('X'); },
      click71: function (e) { console.log('X'); },
      click72: function (e) { console.log('X'); },
      click73: function (e) { console.log('X'); },
      click74: function (e) { console.log('X'); },
      click75: function (e) { console.log('X'); },
      click76: function (e) { console.log('X'); },
      click77: function (e) { console.log('X'); },
      click78: function (e) { console.log('X'); },
      click79: function (e) { console.log('X'); },
      click80: function (e) { console.log('X'); },
      click81: function (e) { console.log('X'); },
      click82: function (e) { console.log('X'); },
      click83: function (e) { console.log('X'); },
      click84: function (e) { console.log('X'); },
      click85: function (e) { console.log('X'); },
      click86: function (e) { console.log('X'); },
      click87: function (e) { console.log('X'); },
      click88: function (e) { console.log('X'); },
      click89: function (e) { console.log('X'); },
      click90: function (e) { console.log('X'); },
      click91: function (e) { console.log('X'); },
      click92: function (e) { console.log('X'); },
      click93: function (e) { console.log('X'); },
      click94: function (e) { console.log('X'); },
      click95: function (e) { console.log('X'); },
      click96: function (e) { console.log('X'); },
      click97: function (e) { console.log('X'); },
      click98: function (e) { console.log('X'); },
      click99: function (e) { console.log('X'); },
      click100: function (e) { console.log('X'); }
    }
  })
};
Session.setDefault("sum", 0);
Template.children.onRendered(function() {
  var that = this;
  var start = new Date().getTime();
  Session.set("start" + that.data, start);
  f(that);

  var i = Meteor.setInterval(function() {
    if ($("#final" + that.data).text()) {
      Meteor.clearInterval(i);
      var end = new Date().getTime();
      var time = end - start;
      Session.set("sum", Session.get("sum") + time);
      if (that.data === 100) {
        console.log("Average: " + Session.get("sum") / 100);
      }

    }
  }, 5);
} );